# Generated by Django 6.0.7 on 2026-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estatus', models.CharField(default='pendiente', max_length=20)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('factura', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
