# Generated by Django 6.0.7 on 2026-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
