# Generated by Django 6.0.7 on 2026-08-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_fecha_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('can_create_order', 'Puede crear órdenes'), ('can_edit_order', 'Puede editar órdenes'), ('can_delete_order', 'Puede eliminar órdenes'), ('can_view_all_orders', 'Puede ver todas las órdenes')]},
        ),
    ]
